name: surchable

services:
  db:
    image: "postgres:14"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB={$SURCHABLE_DB_DATABASE_NAME}"
      - "POSTGRES_USER={$SURCHABLE_DB_USER}"
      - "POSTGRES_PASSWORD={$SURCHABLE_DB_PASSWORD}"
  
  coordinator:
    # image: "ghrc.io/codemicro/surchable/coordinator:latest"
    build:
      context: "."
      dockerfile: "coordinator/Dockerfile"
    env_file:
      - ".env"
  
  webui:
    # image: "ghcr.io/codemicro/surchable/webui:latest"
    build:
      context: "."
      dockerfile: "webui/Dockerfile"
    env_file:
      - ".env"

  crawler:
    # image: "ghcr.io/codemicro/surchable/crawler:latest"
    build:
      context: "."
      dockerfile: "crawler/Dockerfile"
    env_file:
      - ".env"

volumes:
  db: {}