name: surchable

services:
  db:
    image: "postgres:14.4"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ".env"
    ports:
      - 5432:5432
  
  coordinator:
    # image: "ghrc.io/codemicro/surchable/coordinator:latest"
    build:
      context: "."
      dockerfile: "coordinator/Dockerfile"
    env_file:
      - ".env"
    depends_on:
      - db
  
  webui:
    # image: "ghcr.io/codemicro/surchable/webui:latest"
    build:
      context: "."
      dockerfile: "webui/Dockerfile"
    env_file:
      - ".env"
    depends_on:
      - db

  crawler:
    # image: "ghcr.io/codemicro/surchable/crawler:latest"
    build:
      context: "."
      dockerfile: "crawler/Dockerfile"
    env_file:
      - ".env"
    depends_on:
      - coordinator

volumes:
  db: {}
